### ISSUE TITLE
02_blink_a_led.md not converted into .html file

### ISSUE THREAD

**Issue by rogererens** [pollen-robotics/luos-documentation#4]
On https://pollen-robotics.gitbooks.io/luos/content/tutorials/
there is a link to tutorial 3:
https://pollen-robotics.gitbooks.io/luos/content/tutorials/02_blink_a_led.md
which does not do anything (tested in FF and Chrome),
but all other tutorial links are pointing to .html files, not .md files.

**Comment by pierre-rouanet** [comment]
Thanks a lot for all feedback and PR! 
The link was actually broken. It should have been fixed by cfd741587e3bd298da877285a8fa6bf5ff0eb2dc
